Adds ZTP configuration documentation
openshift-kni/telco-ran-tools pull request #57
Opened 2022-11-09 14:12 UTC by alosadagrande

Includes the last part of the documentation: configure ZTP for the factory-cli-tool

Signed-off-by: Alberto Losada <alosadag@redhat.com>

2022-11-09 14:14 UTC, alosadagrande commented
cc/ @donpenney @browsell @obochan-rh

2022-11-14 11:36 UTC, obochan-rh commented
When using the ZTP we need to add a Release notes regarding the limitation of the rootfs isn't loaded from the local mount  and and downloaded from the registry.

2022-11-14 13:41 UTC, donpenney requested changes

2022-11-14 13:41 UTC, donpenney commented on docs/ztp-precaching.md
> +The workflow is officially started by creating declarative configurations for the provisioning of your OpenShift clusters. This manifest is described in a custom resource called `siteConfig`. See tha
The URL here ends up in a bad link with the [oc-mirror] at the end

2022-11-14 13:41 UTC, donpenney commented on docs/ztp-precaching.md
> +Once the clusters are provisioned, the day-2 configuration defined in multiple `PolicyGenTemplate` (PGTs) custom resources will be automatically applied. `PolicyGenTemplate` custom resource is unders
Similar bad link syntax

2022-11-14 13:41 UTC, donpenney commented on docs/ztp-precaching.md
> +* The `extract-ocp.sh` script basically uncompresses and loads the images required in this stage from the disk partition to the local container storage. Fundamentally there are OCP release images and
Are the decoded extraction scripts stored somewhere? Maybe they can be added into the repo with a reference here, noting that they're encoded in this config?

2022-11-14 15:59 UTC, donpenney commented
/retest ci/prow/images

2022-11-14 16:00 UTC, donpenney commented
/retest

2022-11-15 13:14 UTC, donpenney commented
/lgtm

2022-11-15 13:28 UTC, merged